### ISSUE TITLE
feature request: expose command line arguments to compiler

### ISSUE THREAD

**Issue by hems** [polvo/polvo#14]
Would be interesting to expose the "polvo" object to the compilers, so they can for instance check if a release or debug compile.

For instance in debug we could set "linenos" to "true", 

https://github.com/serpentem/polvo/blob/master/src/polvo/compilers/stylus.coffee

Probably useful for other compilers ( :

**Comment by hems** [comment]
I gues its just a matter of passing @cli from "File" to "Compiler" https://github.com/serpentem/polvo/blob/master/src/polvo/core/file.coffee ( :

:8ball:

**Comment by arboleya** [comment]
It'll be delicate to expose all possible command line args in an individual way for all different pre-compilers that's embedded in Polvo.

Referring to line numbers specifically, it should be turned on by default in all compilers for `development`  mode and turned off in `release` mode. It's not currently implemented this way, it's a little messy to be honest, on the other hand it's just a detail.

What was your specific need around this `command line args` thing?

**Comment by hems** [comment]
the idea is just that, turn on debug mode of the compilers when in development mode.

so we have line numbers and filenames on the .css files, etcs [...]

**Comment by arboleya** [comment]
Agreed. This implementation will lead to a better handling of AMD wrappers generated within the `css` contents as well.

**Comment by arboleya** [comment]
Polvo's being revamped from the ground up, now with a plugin's architecture in mind.

So I'm closing this for now, at least here. Anyway it can be implemented very easily in the [Stylus](https://github.com/polvo/polvo-stylus) plugin.

Please feel free to reopen this request there, and specially to send a pull request. :) :beer:
