### ISSUE TITLE
Destroy CSS

### ISSUE THREAD

**Issue by marcelinhov2** [polvo/polvo#15]
It would be great if the Style referent of the view, was destroyed together with the view.

For example, if I set an background color to a div#container, that is the container of all my views, inside the current view style, when I destroy that and render another view on this container, it stay with the background color that was write for the previously view. Did u catch that?

**Comment by arboleya** [comment]
First of all, Polvo doesn't deal with Views, only with files. Styles in polvo is nothing more than auto-executables blocks of CSS code wrapped in an AMD format.

When you require it, it adds itself to the document and returns the reference of the `style` node. You can remove it from the dom from this point.

``` coffeescript
# requiring
Style = require 'path/to/your/style'

# destroying
do ($ Style).remove

# As you will most likely want to re-load this style at some
# point in the future, remember to `undef` it in requirejs so it
# can be loaded and executed again
requirejs.undef Style.id
```
