### ISSUE TITLE
polvo -wr won't work as expected

### ISSUE THREAD

**Issue by hems** [polvo/polvo#20]
It will stop on the "watch" procedure, and don't release.

The expect would be to keep watching and exporting for release.

**Comment by arboleya** [comment]
Currently there's no `-wr` implemented. What are the needs that pushed you to do this instead of the `-ws` in de mode?

https://github.com/serpentem/polvo/blob/master/src/polvo/cli.coffee#L16-L21

**Comment by hems** [comment]
my app uses socket.io and in dev mode the app is only connecting to polvo socket.

ideally it would connect on both servers but for some reason which i still don't know,it doesn't work.

**Comment by hems** [comment]
( closed by accident )

**Comment by arboleya** [comment]
Ok, so this issue isn't about `-wr` but multiple socket.io instances.

In case you find out it's a problem with polvo, please open another issue specifically for this.

**Comment by arboleya** [comment]
Oh well, turns out the issue for this is already open :)
https://github.com/serpentem/polvo/issues/21
