### ISSUE TITLE
problems when connecting to socket.io

### ISSUE THREAD

**Issue by hems** [polvo/polvo#21]
For some reason when using polvo -s, socket.io won't connect in other socket.io server.

For instance if you open another socket server in node an try to socket from the same page which is connected to polvo dev server, it won't receive the connection.

**Comment by arboleya** [comment]
Too brief to understand the cause.

Is this a problem with how Polvo are using socket.io?

Server code:
https://github.com/serpentem/polvo/blob/master/src/polvo/core/tentacle.coffee#L70

Client code:
https://github.com/serpentem/polvo/blob/master/src/polvo/core/optimizer/loader.coffee#L99

**Comment by hems** [comment]
That wasn't a polvo issue.

It was related ( i don't know exactly how ) with the address you use to connect.

For instance if your socket server is http://machine_name.local and you try to connect to http://localhost it wouldn't work. 

After playing a little bit with http://machine_name.local vs http://localhost everything felt into place.
