### ISSUE TITLE
Uncaught TypeError: Cannot read property 'splice' of undefined 

### ISSUE THREAD

**Issue by hems** [polvo/polvo#23]
For some weird reason when compiling my app for release i get the following error ( which doesn't happen on dev mode ).

In order to check better what's going on, i beautified the minified code

Uncaught TypeError: Cannot read property 'splice' of undefined app.js:347
req app.js:347
exports.module.Pages.container app.js:11241
module.exports.Process.run app.js:10364
module.exports.Processes._run_pending_processes app.js:10712
(anonymous function) app.js:10575
module.exports.Processes._destroy_dead_processes app.js:10695
(anonymous function) app.js:10575
(anonymous function) app.js:10619
module.exports.Processes._filter_pending_processes app.js:10639
(anonymous function) app.js:10630
(anonymous function) app.js:10658
(anonymous function) app.js:10330
module.exports.Factory.controller app.js:10863
Process app.js:10328
module.exports.Processes._find_dependency app.js:10657
module.exports.Processes._filter_pending_processes app.js:10627
(anonymous function) app.js:10617
(anonymous function) app.js:10330
(anonymous function) app.js:10876
main app.js:329
(anonymous function)

the beautified code:

```
requirejs = require = req = function (deps, callback, relName, forceSync, alt) {
    if (typeof deps === "string") {
        if (handlers[deps]) {
            return handlers[deps](callback)
        }
        return callDep(makeMap(deps, callback).f)
    } else if (!deps.splice) { <~~ line with problem
```

perhaps this issue is already known:

https://github.com/jrburke/almond/pull/62

https://github.com/jrburke/almond/issues/25

**Comment by arboleya** [comment]
You don't need to prettify anything, for better debugging you can just pass `minify: false` in your `polvo.coffee` config file.

About the error in fact, need to check the stack trace where the error comes from before falling into the almond's method - because every `require` call will point to that, so there's no point in debugging this, but the previous stack calls.

The issues listed is already closed, one more sign that the errors isn't in this code block.

**Comment by hems** [comment]
oh well, my bad. just updated polvo.coffee

**Comment by hems** [comment]
the issue was on my code, which i didn't realize due to the minified version.

my bad.
