### ISSUE TITLE
fail to compile coffeescript node project. due to: 1. not recognize node built-in module 2. why polvo check through "node_modules" ?

### ISSUE THREAD

**Issue by yi** [polvo/polvo#33]
Hi,

I fail to use polvo to compile any coffee-script nodejs project. 

Here is my polvo.yml, did I miss something?

```
server:
  port: 3000
  root: ./dist

input:
  - src

output:
  js: ./dist/server.js

alias:

minify:
  js: false
  css: false

boot: ./src/server

```

error log as following:

```
ty@mba-ace -> ENV=node polvo -c
error Module 'path' not found for 'src/config/config.coffee'
error Module 'path' not found for 'src/config/express.coffee'
error Module './lib-cov/express' not found for 'node_modules/express/index.js'
error Module './lib-cov/connect' not found for 'node_modules/express/node_modules/connect/index.js'
error Module 'events' not found for 'node_modules/express/node_modules/connect/lib/connect.js'
error Module 'path' not found for 'node_modules/express/node_modules/connect/lib/connect.js'
error Module 'fs' not found for 'node_modules/express/node_modules/connect/lib/connect.js'
error Module 'http' not found for 'node_modules/express/node_modules/connect/lib/proto.js'
error Module 'http' not found for 'node_modules/express/node_modules/connect/lib/utils.js'
error Module 'crypto' not found for 'node_modules/express/node_modules/connect/lib/utils.js'
error Module 'url' not found for 'node_modules/express/node_modules/connect/lib/utils.js'
error Module 'path' not found for 'node_modules/express/node_modules/connect/lib/utils.js'
error Module 'crypto' not found for 'node_modules/express/node_modules/cookie-signature/index.js'
error Module 'tty' not found for 'node_modules/express/node_modules/debug/lib/debug.js'
error Module 'http' not found for 'node_modules/express/node_modules/connect/lib/patch.js'
error Module 'url' not found for 'node_modules/express/node_modules/connect/lib/middleware/static.js'
error Module 'stream' not found for 'node_modules/express/node_modules/send/lib/send.js'
error Module 'path' not found for 'node_modules/express/node_modules/send/lib/send.js'
error Module 'http' not found for 'node_modules/express/node_modules/send/lib/send.js'
error Module 'fs' not found for 'node_modules/express/node_modules/send/lib/send.js'
error Module 'path' not found for 'node_modules/express/node_modules/send/node_modules/mime/mime.js'
error Module 'fs' not found for 'node_modules/express/node_modules/send/node_modules/mime/mime.js'
error Module 'http' not found for 'node_modules/express/lib/application.js'
error Module 'buffer' not found for 'node_modules/express/node_modules/buffer-crc32/index.js'

/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:3872
            throw e;
                  ^
Error: Line 9: Illegal return statement
    at throwError (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:1161:21)
    at throwErrorTolerant (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:1172:24)
    at parseReturnStatement (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:2485:13)
    at parseStatement (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:2765:24)
    at parseSourceElement (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:3057:24)
    at parseStatementList (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:2050:25)
    at parseBlock (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:2065:17)
    at parseStatement (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:2740:24)
    at parseIfStatement (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:2200:22)
    at parseStatement (/usr/local/lib/node_modules/polvo/node_modules/esprima/esprima.js:2763:24)

```

**Comment by arboleya** [comment]
Hi, Polvo do not handle NodeJS core modules:
https://github.com/polvo/polvo#dependency-resolution

> ★ Of couse, you won't be able to use NodeJS core modules once inside the Browser, such as fs, process, cluster and so on. The same applies to any other module you may find - if it uses any API not available for in-browser use, you won't be able to use it.

Are you trying to do a hybrid library that works on Browser and in NodeJS as well?

**Comment by yi** [comment]
Hi Arboleya, thank you for the reply. 

What I want to do is to use Polvo to compile a server-side NodeJS project which is written in coffee-script. And I hope Polvo could combine all coffee-script code in 'src' folder into one javascript output file, and wrap each class with CJS. 

It this possible? If so, what command shall I use?

Thanks again.

**Comment by arboleya** [comment]
Hi, the thing is, the main role of Polvo regarding app-assembling is targeting the **browser**.

For pure NodeJS projetcs, there's no point in concatenating files altogether -- which would make it much harder to debug as well.

Instead, you can use the CoffeeScript compiler itself to compile everything, keeping all files individually, like Polvo does with its source code.

Check the Makefile I use for watch/compile the Polvo's source code (which is in coffeescript):
https://github.com/polvo/polvo/blob/master/Makefile#L21-L25

I'm closing this issue, but let me know if I can help you with something else.

**Comment by yi** [comment]
Hi Arboleya,

Thank you for the explanation. I understand the design goal of Polvo. Please close this issue. 

What I'm looking for is an obfuscator tool for server-side nodejs coffee-script project. The problem why coffee -jc + uglify(or google closure) could not suite server-side nodejs project, is because CJS use free `require` variable. And I'm looking for a tool could fake CJS module when combine multiple coffee file into one.

**Comment by arboleya** [comment]
Oh I see, you have a very specific situation.

Maybe you can just avoid joining files? This way you'd end up with multiple minified files, working through the NodeJS builtin require.

**Comment by hems** [comment]
Obfuscating server side code! That sounds like a very specific problem !

Made me curious! :P
