### ISSUE TITLE
don't compile CSS when a compile error occurs

### ISSUE THREAD

**Issue by hems** [polvo/polvo#36]
When editing .styl files i noticed that even when the syntax is broken, polvo builds the CSS and refresh the page ( with a broken CSS file ).

I think in this case we could:
1. Don't compile the CSS
2. Show a red "X" instead of a blue "V" for the CSS file
3. Notify the user using the notification API: https://github.com/polvo/polvo/issues/35

**Comment by arboleya** [comment]
When a file's syntax is broken, this file won't be added to the final `.css`, however it'd be generated. Otherwise you'll keep thinking it `worked`. So I'm closing it.

About the notification, it should be implemented indeed, like it was with Toaster.

**Comment by hems** [comment]
:+1:
