### ISSUE TITLE
Cannot find module 'coffee-script'

### ISSUE THREAD

**Issue by hems** [polvo/polvo#41]
Not sure if there is already an issue for that, but basically if you don't add "coffee-script" to your package.json, you will get a "Cannot find module 'coffee-script'" when executing
"./node_modules/polvo/bin/polvo -ws"

**Comment by hems** [comment]
@arboleya you said you fixed that ¡?

maybe close this ticket then..

**Comment by arboleya** [comment]
Perhaps I should. :+1:

**Comment by hems** [comment]
:8ball: 
team work!
i open the issue, you solve it, i tell you to close!

we like bread and peanut butter, like tea and milk. like tom and jerry. like sandy and junior.
