### ISSUE TITLE
( feature request ) assume vendors are incompatible by default ( polvo.coffee )

### ISSUE THREAD

**Issue by hems** [polvo/polvo#6]
I can the list of incompatible is by far greater than compatible ( 100% ), so i guess we can switch default to incompatible.

```
  incompatible: [
      # theoricus
      'history', 'inflection', 'jquery', 'json'

      # app
      # 'app_vendor'
    ]
```

this way the property will be called "compatible", and only specified when there's compatible vendors

**Comment by arboleya** [comment]
In the actual conjuncture, perfectly makes sense.

**Comment by arboleya** [comment]
It's gonna be completely removed through a new way of including js files that doesn't implement AMD or CJS patterns. See #10
